In [2]:
# Import libraries
import pandas as pd

In [3]:
# Import data and print the first rows 
df = pd.read_csv("PEP1.csv", index_col=0)
df.head()   # Print first 5 rows

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
# Check how many rows and columns we have
print(df.shape)

(1460, 80)

In [5]:
# Check if any columns have missing items. All columns should have N non-null items (N=number of rows). Otherwise they have missing items
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 1 to 1460
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   Alley          91 non-null     object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     1452 non-null   object
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1423 non-null   object
 30  BsmtCond       1423 non-null   object
 31  BsmtExposure   1422 non-null   object
 32  BsmtFinType1   1423 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1422 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchebvGr     1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functiol       1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    object
 57  GarageType     1379 non-null   object
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   object
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1379 non-null   object
 63  GarageCond     1379 non-null   object
 64  PavedDrive     1460 non-null   object
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  PoolQC         7 non-null      object
 72  Fence          281 non-null    object
 73  MiscFeature    54 non-null     object
 74  MiscVal        1460 non-null   int64
 75  MoSold         1460 non-null   int64
 76  YrSold         1460 non-null   int64
 77  SaleType       1460 non-null   object
 78  SaleCondition  1460 non-null   object
 79  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(43)
memory usage: 923.9+ KB

<h2> Data wrangling </h2>

In [ ]:
# DATA WRANGLING ##############################################################################################################
# Some columns are missing values. We have to either fill in these values or delete the entire row
TO DO

<h2>Separate data</h2>
We need to separate the columns into features & target.
We also need to separate the rows into training and testing sets.

In [7]:
# Split dataframe into features and target
X_feature = df.iloc[: , :-2]
Y_target  = df.iloc[: , -1]

print(X_feature.shape) # Confirm that X_feature has the original number of columns minus 1
print(Y_target.shape)  # Confirm that Y_target has 1 column (i.e. it is 1D)

(1460, 78)
(1460,)

In [8]:
# Split data into training and testing. By default, 75% is assigned to training
# Warning: sklearn must be installed with "pip install scykit-learn" instead of the deprecated "pip install sklearn"
from sklearn.model_selection import train_test_split
x_train, y_train, x_test, y_test = train_test_split(X_feature, Y_target, random_state=1)    # random_state ensures rows get selected randomly instead of sequentially

print(x_train.shape)    # Verify size of results
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1095, 78)
(365, 78)
(1095,)
(365,)

<h2>Feature engineering</h2>
Right now we have some columns containing labels (strings). In the next section 'Execute regression' we'll apply a linear regression, which requires all columns to be numerical.

In [ ]:
TO DO

<h2> Execute regression </h2>
(See lesson 3.16)

In [9]:
# We want an equation of the style: a*X1 + b*X2 + c*X3 + d*X4 ... + C = Y
# With this we find the coefficients a, b, c, d... and the constant C.

from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(x_train, y_train)

print("Coefficients: ", str(linreg.coef_))
print("Constant: "    , str(linreg.intercept_))

ValueError: could not convert string to float: 'RL'

In [ ]:
# Confirm regression is valid with test data

In [ ]:
# Pair coefficients with the respective column names

# Show which have a significative influence on the target

In [ ]:



# TRASH ################################################################################################


# 2.Generate a separate dataset for numerical and categorical values
df.describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,46.549315,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,161.319273,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,0.000000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [ ]:
# Find out number of numerical features in the dataset
numerical_feature_columns = list(df._get_numeric_data().columns)
print("Numerical: " + str(len(numerical_feature_columns)) + " columns")

categorical_feature_columns = list(set(df.columns) - set(numerical_feature_columns))
print("Categorical: " + str(len(categorical_feature_columns)) + " columns")

Numerical: 37 columns
Categorical: 43 columns

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df["SalePrice"].unique()

array([208500, 181500, 223500, 140000, 250000, 143000, 307000, 200000,
       129900, 118000, 129500, 345000, 144000, 279500, 157000, 132000,
       149000,  90000, 159000, 139000, 325300, 139400, 230000, 154000,
       256300, 134800, 306000, 207500,  68500,  40000, 149350, 179900,
       165500, 277500, 309000, 145000, 153000, 109000,  82000, 160000,
       170000, 130250, 141000, 319900, 239686, 249700, 113000, 127000,
       177000, 114500, 110000, 385000, 130000, 180500, 172500, 196500,
       438780, 124900, 158000, 101000, 202500, 219500, 317000, 180000,
       226000,  80000, 225000, 244000, 185000, 144900, 107400,  91000,
       135750, 136500, 193500, 153500, 245000, 126500, 168500, 260000,
       174000, 164500,  85000, 123600, 109900,  98600, 163500, 133900,
       204750, 214000,  94750,  83000, 128950, 205000, 178000, 118964,
       198900, 169500, 100000, 115000, 190000, 136900, 383970, 217000,
       259500, 176000, 155000, 320000, 163990, 136000, 153900, 181000,
        84500, 128000,  87000, 150000, 150750, 220000, 171000, 231500,
       166000, 204000, 125000, 105000, 222500, 122000, 372402, 235000,
        79000, 109500, 269500, 254900, 162500, 412500, 103200, 152000,
       127500, 325624, 183500, 228000, 128500, 215000, 239000, 163000,
       184000, 243000, 211000, 501837, 200100, 120000, 475000, 173000,
       135000, 153337, 286000, 315000, 192000, 148500, 311872, 104000,
       274900, 171500, 112000, 143900, 277000,  98000, 186000, 252678,
       156000, 161750, 134450, 210000, 107000, 311500, 167240, 204900,
        97000, 386250, 290000, 106000, 192500, 148000, 403000,  94500,
       128200, 216500,  89500, 185500, 194500, 318000, 262500, 110500,
       241500, 137000,  76500, 276000, 151000,  73000, 175500, 179500,
       120500, 266000, 124500, 201000, 415298, 228500, 244600, 179200,
       164700,  88000, 153575, 233230, 135900, 131000, 167000, 142500,
       175000, 158500, 267000, 149900, 295000, 305900,  82500, 360000,
       165600, 119900, 375000, 188500, 270000, 187500, 342643, 354000,
       301000, 126175, 242000, 324000, 145250, 214500,  78000, 119000,
       284000, 207000, 228950, 377426, 202900,  87500, 140200, 151500,
       157500, 437154, 318061,  95000, 105900, 177500, 134000, 280000,
       198500, 147000, 165000, 162000, 172400, 134432, 123000,  61000,
       340000, 394432, 179000, 187750, 213500,  76000, 240000,  81000,
       191000, 426000, 106500, 129000,  67000, 241000, 245500, 164990,
       108000, 258000, 168000, 339750,  60000, 222000, 181134, 149500,
       126000, 142000, 206300, 275000, 109008, 195400,  85400,  79900,
       122500, 212000, 116000,  90350, 555000, 162900, 199900, 119500,
       188000, 256000, 161000, 263435,  62383, 188700, 124000, 178740,
       146500, 187000, 440000, 251000, 132500, 208900, 380000, 297000,
        89471, 326000, 374000, 164000,  86000, 133000, 172785,  91300,
        34900, 430000, 226700, 289000, 208300, 164900, 202665,  96500,
       402861, 265000, 234000, 106250, 184750, 315750, 446261, 200624,
       107500,  39300, 111250, 272000, 248000, 213250, 179665, 229000,
       263000, 112500, 255500, 121500, 268000, 325000, 316600, 135960,
       142600, 224500, 118500, 146000, 131500, 181900, 253293, 369900,
        79500, 185900, 451950, 138000, 319000, 114504, 194201, 217500,
       221000, 359100, 313000, 261500,  75500, 137500, 183200, 105500,
       314813, 305000, 165150, 139900, 209500,  93000, 264561, 274000,
       370878, 143250,  98300, 205950, 350000, 145500,  97500, 197900,
       402000, 423000, 230500, 173500, 103600, 257500, 372500, 159434,
       285000, 227875, 148800, 392000, 194700, 755000, 335000, 108480,
       141500,  89000, 123500, 138500, 196000, 312500, 361919, 213000,
        55000, 302000, 254000, 179540,  52000, 102776, 189000, 130500,
       159500, 341000, 103000, 236500, 131400,  93500, 239900, 299800,
       236000, 265979, 260400, 275500, 158900, 179400, 215200, 337000,
       264132, 216837, 538000, 134900, 102000, 395000, 221500, 175900,
       187100, 161500, 233000, 107900, 160200, 146800, 269790, 143500,
       485000, 582933, 227680, 135500, 159950, 144500,  55993, 157900,
       224900, 271000, 224000, 183000, 139500, 232600, 147400, 237000,
       139950, 174900, 133500, 189950, 250580, 248900, 169000, 200500,
        66500, 303477, 132250, 328900, 122900, 154500, 118858, 142953,
       611657, 125500, 255000, 154300, 173733,  75000,  35311, 238000,
       176500, 145900, 169990, 193000, 117500, 184900, 253000, 239799,
       244400, 150900, 197500, 172000, 116500, 214900, 178900,  37900,
        99500, 182000, 167500,  85500, 178400, 336000, 159895, 255900,
       117000, 395192, 195000, 197000, 348000, 173900, 337500, 121600,
       206000, 232000, 136905, 119200, 227000, 203000, 213490, 194000,
       287000, 293077, 310000, 119750,  84000, 315500, 262280, 278000,
       139600, 556581,  84900, 176485, 200141, 185850, 328000, 167900,
       151400,  91500, 138800, 155900,  83500, 252000,  92900, 176432,
       274725, 134500, 184100, 133700, 118400, 212900, 163900, 259000,
       239500,  94000, 424870, 174500, 116900, 201800, 218000, 235128,
       108959, 233170, 245350, 625000, 171900, 154900, 392500, 745000,
       186700, 104900, 262000, 219210, 116050, 271900, 229456,  80500,
       137900, 367294, 101800, 138887, 265900, 248328, 465000, 186500,
       169900, 171750, 294000, 165400, 301500,  99900, 128900, 183900,
       378500, 381000, 185750,  68400, 150500, 281000, 333168, 206900,
       295493, 111000, 156500,  72500,  52500, 155835, 108500, 283463,
       410000, 156932, 144152, 216000, 274300, 466500,  58500, 237500,
       377500, 246578, 281213, 137450, 193879, 282922, 257000, 223000,
       274970, 182900, 192140, 143750,  64500, 394617, 149700, 149300,
       121000, 179600,  92000, 287090, 266500, 142125, 147500])